image: Visual Studio 2015

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\qpentago
# git clone --depth 1
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14

install:
    - call ci/appveyor/win-set-cmake_generator.bat %TOOLCHAIN% %PLATFORM%
    - call ci/appveyor/win-set-cmake_qt_dir.bat %TOOLCHAIN% %PLATFORM%

build_script:
    - mkdir build
    - cd build
    - cmake .. -G"%CMAKE_GENERATOR%" -DCMAKE_PREFIX_PATH=%CMAKE_QT_DIR%
    - cmake --build . --config %CONFIGURATION%

